//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFicheWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class etudiant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public etudiant()
        {
            this.acheter = new HashSet<acheter>();
        }
    
        public int matricule { get; set; }
        public int idStatut { get; set; }
        public int idSpecialite { get; set; }
        public string nomEtudiant { get; set; }
        public string prenomEtudiant { get; set; }
        public string mdp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acheter> acheter { get; set; }
        public virtual specialite specialite { get; set; }
        public virtual statut statut { get; set; }
    }
}
