//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFicheWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fiche_revisionEntities : DbContext
    {
        public fiche_revisionEntities()
            : base("name=fiche_revisionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acheter> acheter { get; set; }
        public virtual DbSet<etudiant> etudiant { get; set; }
        public virtual DbSet<fiche> fiche { get; set; }
        public virtual DbSet<specialite> specialite { get; set; }
        public virtual DbSet<statut> statut { get; set; }
        public virtual DbSet<theme_fiche> theme_fiche { get; set; }
    }
}
